const BASE_URL = process.env.BASE_URL || "http://localhost:3000";
const movies = [
  {
    id: 1,
    img: `${BASE_URL}/images/a_quiet_place.jpg`,
    name: "A Quiet Place",
    category: "Thriller",
    rating: "PG-13",
    time: "2h 5min",
  },
  {
    id: 2,
    img: `${BASE_URL}/images/a_quiet_place_part_ii.jpg`,
    name: "A Quiet Place Part II",
    category: "Thriller",
    rating: "PG-13",
    time: "2h 5min",
  },
  {
    id: 3,
    img: `${BASE_URL}/images/the_batman.jpg`,
    name: "The Batman",
    category: "Action",
    rating: "PG-13",
    time: "2h 5min",
  },
  {
    id: 4,
    img: `${BASE_URL}/images/how_to_train_your_dragon.jpg`,
    name: "How To Train Your Dragon",
    category: "Animation",
    rating: "PG-13",
    time: "2h 5min",
  },
  {
    id: 5,
    img: `${BASE_URL}/images/the_bridge_to_terabithia.jpg`,
    name: "The Bridge to Terabithia",
    category: "Drama",
    rating: "PG-12",
    time: "2h 5min",
  },
  {
    id: 6,
    img: `${BASE_URL}/images/snow_white_and_the_huntsman.jpg`,
    name: "Snow White and the Huntsman",
    category: "Fantasy",
    rating: "PG-13",
    time: "2h 5min",
  },
  {
    id: 7,
    img: `${BASE_URL}/images/along_for_the_ride.jpg`,
    name: "Along for the Ride",
    category: "Drama",
    rating: "PG-13",
    time: "2h 5min",
  },
  {
    id: 8,
    img: `${BASE_URL}/images/the_kingsman.jpg`,
    name: "The King's Man",
    category: "Action",
    rating: "PG-13",
    time: "2h 5min",
  },
  {
    id: 9,
    img: `${BASE_URL}/images/insidious_the_red_door.jpg`,
    name: "Insidious: The Red Door",
    category: "Horror",
    rating: "PG-16",
    time: "2h 5min",
  },
  {
    id: 10,
    img: `${BASE_URL}/images/not_cinderella's_type.jpg`,
    name: "Not Cinderella's Type",
    category: "Drama",
    rating: "PG-13",
    time: "2h 5min",
  },
  {
    id: 11,
    img: `${BASE_URL}/images/hitman.jpg`,
    name: "The Hitman's Wife Bodyguard",
    category: "Action",
    rating: "PG-13",
    time: "2h 5min",
  },
  {
    id: 12,
    img: `${BASE_URL}/images/the_witches.jpg`,
    name: "The Witches",
    category: "Fantasy",
    rating: "PG-13",
    time: "2h 5min",
  },
  {
    id: 13,
    img: `${BASE_URL}/images/enchanted.jpg`,
    name: "Enchanted",
    category: "Animation",
    rating: "PG-13",
    time: "2h 5min",
  },
  {
    id: 14,
    img: `${BASE_URL}/images/a_tribe_called_judah.png`,
    name: "A Tribe called Judah",
    category: "Drama",
    rating: "PG-12",
    time: "2h 5min",
  },
  {
    id: 15,
    img: `${BASE_URL}/images/the_wedding_party.jpg`,
    name: "The Wedding Party",
    category: "Drama",
    rating: "PG-13",
    time: "2h 5min",
  },
];

module.exports = movies;
